"use client";

import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import Image from "next/image";
import { useRef } from "react";
import { EASE, fadeUp, VIEWPORT } from "@/lib/motion";

/* ---------------------------------------------------------------- Reveal */

export function Reveal({
  children,
  className,
  delay = 0,
  as = "div",
}: {
  children: React.ReactNode;
  className?: string;
  delay?: number;
  as?: "div" | "li" | "p" | "span";
}) {
  const Comp = motion[as];
  return (
    <Comp
      className={className}
      initial="hidden"
      whileInView="show"
      viewport={VIEWPORT}
      variants={fadeUp}
      custom={delay}
    >
      {children}
    </Comp>
  );
}

/* ------------------------------------------------------------ AccentLine */

export function AccentLine({
  className = "",
  delay = 0,
  origin = "start",
}: {
  className?: string;
  delay?: number;
  origin?: "start" | "end" | "center";
}) {
  // Logical origin: grows from the reading start (right edge in RTL).
  const originCls = origin === "center" ? "origin-center" : origin === "end" ? "origin-right rtl:origin-left" : "origin-left rtl:origin-right";
  return (
    <motion.span
      aria-hidden
      className={`block h-px bg-ember ${originCls} ${className}`}
      initial={{ scaleX: 0 }}
      whileInView={{ scaleX: 1 }}
      viewport={{ once: true, amount: 0.8 }}
      transition={{ duration: 1.1, ease: EASE, delay }}
    />
  );
}

/* -------------------------------------------------------- SectionHeading */

export function SectionHeading({
  index,
  label,
  title,
  id,
  className = "",
  align = "left",
}: {
  index?: string;
  label: string;
  title: React.ReactNode;
  id?: string;
  className?: string;
  align?: "left" | "center";
}) {
  const centered = align === "center";
  return (
    <div className={`${centered ? "text-center" : ""} ${className}`}>
      <Reveal
        className={`eyebrow flex items-center gap-4 ${centered ? "justify-center" : ""}`}
      >
        {index && <span className="text-ember">{index}</span>}
        <AccentLine className="w-10" />
        <span>{label}</span>
      </Reveal>
      <Reveal delay={0.08}>
        <h2
          id={id}
          className="display mt-4 text-[clamp(2.25rem,7.4vw,4.4rem)] text-bone text-balance"
        >
          {title}
        </h2>
      </Reveal>
    </div>
  );
}

/** "FITologist" set in the brand's casing with the orange FIT, for use inside uppercase headings. */
export function BrandWord() {
  return (
    <span className="normal-case">
      <span className="text-ember">FIT</span>ologist
    </span>
  );
}

/* ---------------------------------------------------------- BlendedImage */

type Fade = { t?: string; r?: string; b?: string; l?: string };

/**
 * Frameless photograph that dissolves into the section background
 * (CSS mask via `.blend-edges`), with a subtle 1.03 → 1 entrance and gentle
 * parallax. The masked edges also hide any parallax travel, so no overscan crop.
 */
export function BlendedImage({
  src,
  alt,
  sizes,
  className = "",
  imgClassName = "object-cover",
  fade,
  strength = 3,
  quality = 85,
  mask,
}: {
  src: string;
  alt: string;
  sizes: string;
  className?: string;
  imgClassName?: string;
  fade?: Fade;
  /** Custom mask-image (e.g. a radial vignette) replacing the default edge fade */
  mask?: string;
  /** percentage of vertical parallax travel */
  strength?: number;
  quality?: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const reduce = useReducedMotion();
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] });
  const y = useTransform(scrollYProgress, [0, 1], [`-${strength}%`, `${strength}%`]);
  const fadeVars = {
    ...(fade?.t && { "--fade-t": fade.t }),
    ...(fade?.r && { "--fade-r": fade.r }),
    ...(fade?.b && { "--fade-b": fade.b }),
    ...(fade?.l && { "--fade-l": fade.l }),
    ...(mask && { maskImage: mask, WebkitMaskImage: mask }),
  } as React.CSSProperties;

  return (
    <div ref={ref} className={`blend-edges relative ${className}`} style={fadeVars}>
      <motion.div className="absolute inset-0" style={reduce ? undefined : { y }}>
        <motion.div
          className="absolute inset-0"
          initial={{ scale: 1.03 }}
          whileInView={{ scale: 1 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 1.6, ease: EASE }}
        >
          <Image src={src} alt={alt} fill sizes={sizes} quality={quality} className={imgClassName} />
        </motion.div>
      </motion.div>
    </div>
  );
}

/* --------------------------------------------------------- LogoWatermark */

/**
 * The FITologist mark as a barely-visible background element (≈3% opacity).
 * Uses the transparent crop generated by scripts/optimize-images.mjs.
 */
export function LogoWatermark({
  className = "",
  opacity = 0.03,
  travel = 18,
}: {
  className?: string;
  opacity?: number;
  travel?: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const reduce = useReducedMotion();
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] });
  const y = useTransform(scrollYProgress, [0, 1], [`${travel}%`, `-${travel}%`]);

  return (
    <div
      ref={ref}
      aria-hidden
      className="pointer-events-none absolute inset-0 overflow-hidden select-none"
    >
      <motion.div
        className={`absolute ${className}`}
        style={reduce ? { opacity } : { y, opacity }}
      >
        <Image
          src="/images/logo-mark.png"
          alt=""
          width={606}
          height={474}
          sizes="(min-width: 1024px) 60vw, 110vw"
          className="h-auto w-full"
        />
      </motion.div>
    </div>
  );
}
